# Generated by Django 3.1.2 on 2020-10-23 21:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gam_account_no', models.CharField(db_index=True, max_length=32)),
                ('order_id', models.BigIntegerField(db_index=True)),
                ('order_name', models.CharField(db_index=True, max_length=64)),
                ('advertiser', models.CharField(db_index=True, max_length=64)),
                ('trafficker', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_id', models.BigIntegerField(db_index=True)),
                ('li_name', models.CharField(db_index=True, max_length=64)),
                ('li_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('li_inventory', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), size=None)),
                ('li_geo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), size=None)),
                ('li_custom_targeting', django.contrib.postgres.fields.hstore.HStoreField()),
                ('li_sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=32), size=None)),
                ('li_status', models.CharField(blank=True, max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.order')),
            ],
        ),
    ]
